image:
  repository: viktory11q8/ski-rental
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80
  targetPort: 5000

serviceAccount:
  create: true
  name: ""
  annotations: {}
  automountServiceAccountToken: true

ingress:
  enabled: true
  className: nginx
  annotations:

    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 10m
  hosts:
    - host: ski-rental.example.com
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: ski-rental
              port:
                number: 80
